<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use View;
use Auth;
use Validator;
use Session;
use DB;
use Redirect;
use Form;
use App\Http\Controllers\FuncionesControllers;

use PDF;

?>
@include('layout.header_encuesta')
	
	{!! Form::open(array('url' => 'prueba_op/encuesta_5_1_3-'.$id_au, 'method' => 'post', 'class' =>  "form-horizontal", 'files'=>true)) !!}
<input type="hidden" name="id_au" value="<?=$id_au?>">
<!-- Image Map Generated by http://www.image-map.net/ -->

<map name="image-map">
    <area coords="135,116,30,54" shape="rect" onclick="escribir(1);">
    <area coords="156,54,258,117" shape="rect" onclick="escribir(2);">
    <area coords="278,56,376,114" shape="rect" onclick="escribir(3);">
    <area coords="32,148,129,214" shape="rect" onclick="escribir(4);">
    <area coords="156,150,262,212" shape="rect" onclick="escribir(5);">
    <area coords="279,149,378,210" shape="rect" onclick="escribir(6);">
    <area coords="34,234,132,299" shape="rect" onclick="escribir(7);">
    <area coords="155,237,261,301" shape="rect" onclick="escribir(8);">
    <area coords="280,237,373,307" shape="rect" onclick="escribir(9);">
    <area coords="30,331,376,403" shape="rect" onclick="escribir(0);">
</map>

	<div id="encuesta_1" align="center" style="width: 100%; background: transparent; margin:0px; margin: auto; padding: 0px;">
		<div align="center">							
			<div class="" style="background-color: transparent">									
				<!-- Smart Wizard -->
					<div align="center"><strong><h1 style="color: #1abb9c; texty-align: center">Agudeza Perceptiva</h1></strong></div>
					<div id="valor"></div>
					<div id="wizard_1" align="center" class="form_wizard wizard_horizontal" style="margin: 0px; padding: 0px; text-align: center">
						<?php 				
						
							$sql = "select * from preguntas_op where id_pruebas=1 and id_preguntas>83 order by orden limit 9";
							//echo $sql;
							$data=DB::select($sql);
							
							$cantidad_1=1;
							
							foreach ($data as $data) {
								$id_pregunta=$data->id_preguntas;
								$pregunta=$data->nombre;
								$respuesta=$data->respuesta;												
								//$valor=$respuesta;
								$valor="";
								
								if ($cantidad_1==1)
									echo "<script>pregunta_actual_co=".$id_pregunta."</script>";
								
								echo "
									<script>
										respuesta_actual_co[".$id_pregunta."]=".$respuesta.";
									</script>
								";
								?>
								<div id="step-<?php echo $cantidad_1; ?>" align="center" style="line-height: 50%; text-align: center;">
									<form name="forma_<?php echo $cantidad_1; ?>" class="form-horizontal">
										<div align="center" style="top:0px; position: relative;">									
											<?php
											echo "<table border=0 style='padding:50px' align='center'><tr>";
											echo "<td align='center'>
													<h3><strong>".$pregunta."</strong>
													<input maxlength='10' class='clase' onblur='verificar_forma(1,".$id_pregunta.",\"".$respuesta."\")' onKeyPress='return soloNumeros(event)' style='width:250px; text-align: center' type='text' name='ap_".$id_pregunta."' id='ap_".$id_pregunta."' value='".$valor."'></h3>
												</td>";
											echo "</tr></table><br />";
											?>
										</div>
									</form>
								</div>
								<?php
								$cantidad_1++;
							}
						?>
						<ul class="wizard_steps" style="top: 35px">
							<?php												
							for ($i=1; $i<($cantidad_1); $i++) { ?>
							<li>
								<a href="#step-<?php echo $i; ?>">
									<span class="step_no"><?php echo $i; ?></span>
								</a>
							</li>
							<?php } ?>
						</ul>							
					<!-- End SmartWizard Content -->						
				</div>
			</div>
		</div>
		
		<img src="../imagenes/prueba_op/telefono.jpg" usemap="#image-map" />
	</div>

	
<table border=0 width="100%" align="center">
	<tr>	
		<td align="center">
			<!--PREGUNTAS-->
			<table background-color="#989898" align="center" border=0>
				<tr>
					<td>			
			<!--FIN PREGUNTAS-->				
			
					</td>
				</tr>
			</table>											
		</td>
	</tr>
</table>
					</div>		
		{!! Form::close() !!}
@include('layout.footer_encuesta')
